- name: "Install node "
  become: yes
  apt:
    name: ["nodejs"]
    state: latest
    
- name: "Install npm "
  become: yes
  apt:
    name: ["npm"]
    state: latest
    
- name: "Install pm2 "
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes 

- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory


- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    unzip dist.zip
    rm -rf dist.zip

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    sudo apt-get install -y node.js
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/backend_app
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu