---
- name: "update apt packages"
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes
    
- name: "remove dependencies that are no longer required"
  apt: 
    upgrade: yes
    
- name: "install nodejs"
  apt:
    name: nodejs
    state: present
    
- name: "Install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes
    
- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory
    
- name: "unarchive backend files to app directory"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app
    
- name: "Installing Node Dependencies for deply backend on ec2"
  shell: |
    cd ~/backend-app
    npm i

- name: "Check app files"
  shell: |
    export
    cd ~/backend-app
    ls -R ~/backend-app
    
- name: "Executing Node app with pm2"
  args:
    chdir: ~/backend_app/dist
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
  shell: |
    pm2 stop default
    pm2 start main.js
  register: execute_node
    
- name: print message
  debug:
    msg:"{{execute_node.stdout_lines}}"
    
- name: "configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/user/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
