 name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: install node
  shell: |
    curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash - && sudo apt-get install -y nodejs

- name: "Install npm "
  become: yes
  apt:
    name: ["npm"]
    state: latest
    
- name: "Install pm2 "
  become: yes
  npm:
    name: pm2
    global: yes
    state: present
    production: yes 

- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory


- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    unzip dist.zip
    rm -rf dist.zip

- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    npm install

- name: "Executing node"
  shell: |
    export
    cd ~/backend_app
    pm2 start main.js
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu